apiVersion: v1
kind: Pod
metadata:
  name: safebank-app
  namespace: safebank-will
  labels:
    app: safebank-app
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
